# Generated by Django 4.2.6 on 2023-11-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_remove_textpart_text_textpart_text_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpart',
            name='texts_en',
            field=models.CharField(default='', max_length=500),
        ),
    ]
